### ISSUE TITLE
WebUI Issue when Scanning

### ISSUE THREAD

**Issue by BrendanThompson** [mikenowak/docker-nessus#1] opened 2017-07-04 05:42 UTC
Hi there,

I am running the latest version of the docker container, which has updated Nessus to the latest version as well.

When I run a scan on a network it tanks the WebUI and I'm no longer able to login. The container doesn't look as though it's doing too much the RAM usage is under 20% of available and the CPU usage is about a full CPU. 

Just wondering if this is something that you've seen before?

**Comment by mikenowak** [comment] 2017-07-04 08:22
Hi @BrendanThompson 

no matter how silly it may sound, - are you accessing the WebUI over a WAN link by a chance?

**Comment by BrendanThompson** [comment] 2017-07-11 02:53
Hey Mike,

I’m accessing it all internally, just on local host :)

Sent from my iPhone

On 4 Jul 2017, at 18:22, Mike Nowak <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @BrendanThompson<https://github.com/brendanthompson>

no matter how silly it may sound, - are you accessing the WebUI over a WAN link by a chance?

**Comment by mikenowak** [comment] 2017-07-11 11:03
hi @BrendanThompson, ok fair enough - the only reason I asked about WAN is that I have a similar issue over a WAN link - but thats probably latency between Asia and Europe more than anything.

The only other thing that comes to mind is that the scan saturates your NIC - and nessus can really do that.

So the question is - are there any other containers running on the same host where your Nessus is? Are they reachable during the scan?

I suggest running iftop or something similar on the physical host to see what it happening in the network.

You may also try to enable "Slow down the scan when network congestion is detected" under Performance Options (see Policy -> Settings -> Advanced), and see if this improves the situation in any way.

Let me know how you get on.

**Comment by BrendanThompson** [comment] 2017-07-17 05:16
@mikenowak I tried telnetting from my localhost to a remote box and was able to do so, however I was unable to from within the container.

**Comment by mikenowak** [comment] 2018-02-04 09:44
its bit dated, and I was unable to reproduce - so closing off

**Closed by mikenowak** 2018-02-04 09:44 UTC
